#!/bin/bash

DEBUG_MODE=false
DEBUG_PORT=15676
ENABLE_TELEMETRY=false

while getopts dg flag
do
    case "${flag}" in
        d) DEBUG_MODE=true;;
        g) ENABLE_TELEMETRY=true;;
    esac
done

CMD=""
if [ $DEBUG_MODE = true ]; then
    CMD="debugpy --wait-for-client --listen 0.0.0.0:$DEBUG_PORT -m uvicorn app:app --host 0.0.0.0 --port 80 --reload"
fi

trap "echo -ne '\nstopping container...' && docker stop refinery-neural-search > /dev/null 2>&1 && echo -ne '\t\t [done]\n'" EXIT

echo -ne 'stopping old container...'
docker stop refinery-neural-search > /dev/null 2>&1
echo -ne '\t [done]\n'

echo -ne 'building container...'
docker build -t refinery-neural-search-dev -f dev.Dockerfile .
echo -ne '\t\t [done]\n'

echo -ne 'starting...'
docker run -d --rm \
--name refinery-neural-search \
-p $DEBUG_PORT:$DEBUG_PORT \
-p 7063:80 \
-e POSTGRES=postgresql://postgres:kern@graphql-postgres:5432 \
-e QDRANT_PORT=6333 \
-e ENABLE_TELEMETRY=$ENABLE_TELEMETRY \
--mount type=bind,source="$(pwd)"/,target=/app \
-v /var/run/docker.sock:/var/run/docker.sock \
--network dev-setup_default \
--log-driver=loki \
--log-opt loki-url="http://$HOST_IP:3100/loki/api/v1/push" \
refinery-neural-search-dev $CMD > /dev/null 2>&1
echo -ne '\t\t\t [done]\n'

if [ $DEBUG_MODE = true ]; then
    echo -e "\033[0;33muse VSCode Debugger (Python Debugger: refinery-neural-search) to start the service\033[0m"
fi
docker logs -f refinery-neural-search
